config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'


  get 'static_pages/triumph'
  
  get 'static_pages/activityinside'
  
  get 'static_pages/meeting'
  
  get 'static_pages/charity'

  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/tuitionscholar', to: 'static_pages#tuitionscholar'
  get '/admission', to: 'static_pages#admission'
  get '/activity', to: 'static_pages#activity'
 
#   get '/triumph', to: 'static_pages#triumph'
  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<% provide(:title, 'Footer') %>
<footer class="footer">

<p>
About us Ms.Vittunyuta Maeprasark, Ms.Kwankaew Uttama, Ms.Jiranan Patrathamakul, Ms.Pannapat Panpakdee, Ms.Pimwalun Witchawanitchanun.
</p>
<nav>
<ul>

<li>Follow us 02-797-0999 x 1403&thinsp;
    <a href="https://www.facebook.com/KasetsartCPE" rel="nofollow">
        <img src="https://www.cpe.ku.ac.th/wp-content/themes/academica_pro/images/social/facebook_small.png" width="16" height="16" alt="">
    </a>
    <a href="http://www.youtube.com/user/admissionengku" rel="nofollow">
        <img src="https://www.cpe.ku.ac.th/wp-content/themes/academica_pro/images/social/youtube_small.png" width="16" height="16" alt="">
    </a>
</li>
</ul>
</nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all',
  'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"> </script>
  <![endif]--> 
</head> 
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "CPEWEB", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right"> 
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Activity", activity_path %></li>
          <li><%= link_to "Addmission", admission_path %></li>
          <li><%= link_to "Tuition&Scholarships", tuitionscholar_path %></li>
          <li><%= link_to "Contact US", contact_path %></li>
        </ul> 
      </nav>
    </div>
  </header>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body> 
</html>

app/views/layouts/footer.html.erb
<% provide(:title, 'Footer') %>
<footer class="footer">

<p>
About us Ms.Vittunyuta Maeprasark,Ms.Kwankaew Uttama,Ms.Jiranan Patrathamakul,
Ms.Pannapat Panpakdee,Ms.Pimwalun Witchawanitchanun.
</p>
<nav>
<ul>

<li>Follow us 02-797-0999 x 1403</li>
    <a href="https://www.facebook.com/KasetsartCPE" rel="nofollow">
        <img src="https://www.cpe.ku.ac.th/wp-content/themes/academica_pro/images/social/facebook_small.png" width="16" height="16" alt="">
    </a>
    <a href="http://www.youtube.com/user/admissionengku" rel="nofollow">
        <img src="https://www.cpe.ku.ac.th/wp-content/themes/academica_pro/images/social/youtube_small.png" width="16" height="16" alt="">
    </a>


</ul>
</nav>
</footer>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>History</h1>
<h3>OVERVIEW OF OUR DEPARTMENT</h3>

<p>&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;Our Department of Computer Engineering in the Faculty of Engineering, Kasetsart University, was founded on February 3rd, 1989 with the mission to teach, research, develop and service in related areas such that our graduates will meet the market need in Thailand as well as the region. Currently, the department is offering degrees in computer engineering, information technology, software engineering and knowledge engineering as follow:</p>

<ul style="list-style-type:circle">
  <li>Bachelor of Engineering in Computer Engineering</li>
  <li>Bachelor of Engineering in Software and Knowledge Engineering</li>
  <li>Master of Science in Information Technology</li>
  <li>Master of Engineering in Computer Engineering</li>
  <li>Doctor of Engineering in Computer Engineering</li>
</ul>

<p>&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;In addition to our course offerings, many research units have been founded by faculty members in our department, ranging from development centers and specific research centers to research laboratories. These units are either under the umbrella of the university, the faculty or our department. This leads to the cooperation in research within the university as well as institutions inside and outside the country. Most of our researches have funding from the university, the Royal Thai government, foreign governments and several companies both inside and outside the country.</p>

<p>&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;Our department encourages our students, staffs, researchers and faculty members to continuously and repeatedly advance the knowledge in the area. We support our members in several ways from participating in academic training, publishing papers in conferences and seeking cooperation with experts in related area worldwide.</p>

<p>&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;Our vision is to continuously take a lead role in education, training and research in computer engineering to make our graduates fully prepared and ready for the rapidly growing industry in Thailand as well as the region.</p>

app/views/static_pages/activity.html.erb
<head>
    <center><h1>กิจกรรม</h1></center>
</head>

<body>
    <center><div id=body>
        <p><a href="http://finalisp-aommoacloud9.c9users.io:8080/static_pages/activityinside"><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2015/03/activity_02.jpg"></a></p>
        <br>
        <p><a href="http://finalisp-aommoacloud9.c9users.io:8080//static_pages/meeting"><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2015/03/activity_04.jpg"></a></p>
        <br>
        <a href="http://finalisp-aommoacloud9.c9users.io:8080//static_pages/charity"><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2015/03/activity_01_edit1.jpg"></a>
    </div></center>
</body>

app/views/static_pages/activityinside.html.erb
<center><h1>กิจกรรมภายในภาควิชา</h1></center>
<body>
    <div id=box1>
    <h2>Exceed Camp</h2>
    <center><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2015/03/exceed_section.jpg" width="50%"></center>
    <p><br>
        ค่ายทะลุฟ้า หรือ ค่ายพัฒนาซอฟต์แวร์ในสภาพการทำงานร่วมแบบเปิดกว้าง หรือ ค่าย eXceed มีวัตถุประสงค์เพื่อเป็นกิจกรรมหลักด้านการฝึกทักษะทั้งด้านวิชาการและสังคมให้แก่นิสิตของภาควิชา
        ค่ายทะลุฟ้าในแต่ละปีจะมีธีมประจำปีซึ่งเป็นธีมที่จะกำหนดโปรเจคของน้องๆ ในค่าย โดยในช่วงระยะเวลาค่ายพี่ๆ จะสอนพื้นฐานความรู้เบื้องต้นให้กับน้องๆ เพื่อนำไปใช้ในการทำโปรเจค
    </p>
    <a href="https://www.cpe.ku.ac.th/?page_id=1417" class="buttonD">รายละอียด</a>
    </div>
    <br>
    <div id=box2>
        <h2>Freshy Camp</h2>
    <center><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2015/03/freshy_section.jpg" width="50%"></center>
    <p><br>Freshy Camp หรือที่รู้จักในชื่อค่ายรับน้อง คือค่ายสำหรับนิสิตเฟรชชี่ภาคคอม โดยจุดประสงค์ของค่ายคือเพื่อให้เฟรชชี่แต่ละคนได้รู้จักกับเพื่อนใหม่และทำความรู้จักกับพี่ๆ ภาคคอมไปด้วยในเวลาเดียวกัน ระหว่างค่ายจะมีกิจกรรมหลายอย่างเช่น กิจกรรมสันทนาการจากพี่ๆ, กิจกรรมงานวัดจำลองที่น้องเฟรชชี่ได้สร้างซุ้มเกมของตัวเอง โดยหลังจากจบค่ายนี้แล้วน้องๆ จะได้รู้จักกับเพื่อนใหม่จากต่างโรงเรียนและได้สร้างความคุ้นเคยกับพี่ๆ ภาคคอมไปในเวลาเดียวกัน</p>
    <a href="https://www.cpe.ku.ac.th/?page_id=1407" class="buttonD">รายละอียด</a>
    </div>
    <br>
    <div id=box3>
        <h2>Toffy Camp</h2>
    <center><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2015/03/toffeecamp_section.jpg" width="50%"></center>
    <p><br>ค่ายเทคโนโลยีแห่งอนาคตเพื่อเยาวชนครั้งที่ 2 ได้จัดขึ้นเพื่ออบรมเยาวชนยุคใหม่ ให้เรียนรู้การ เขียนโปรแกรมโดยใช้ภาษา C# การต่อวงจรดิจิตอลเบื้องต้น การเขียน Android App Inventor อบรมให้ เยาวชนยุคใหม่ ก้าวทันเทคโนโลยีและสามารถนำเทคโนโลยีไปประยุกต์ใช้ในชีวิตประจ าวันได้ รวมทั้งเป็น การแนะแนวทางการศึกษาต่อทางด้านวิศวกรรมคอมพิวเตอร์อีกด้วย</p>
    <a href="https://www.cpe.ku.ac.th/?page_id=1407" class="buttonD">รายละอียด</a></div>
    <br>
    <div id=box4>
        <h2>SOS Camp</h2>
    <center><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2015/03/sos_section.jpg" width="50%"></center>
    <p><br>ค่ายนี้จัดขึ้นเพื่อเฟรชชี่ที่พึ่งเข้าใหม่ เพื่อเป็นการปูพื้นฐานการเขียนโปรแกรมก่อนที่จะเริ่มเรียนจริง ค่ายนี้จะช่วยให้น้องๆ มีชีวิตรอดจากวิชาเรียนต่างๆ ในภาคคอมได้ โดยค่ายนี้จะเน้นติววิชา OOP (Object-oriented programming) เป็นหลัก น้องๆ ที่เข้าร่วมค่ายนี้จะได้ความรู้และวิทยายุทธเพื่อให้น้องๆ สามารถอยู่รอดในยุทธจักรนี้ได้</p>
    <a href="https://www.cpe.ku.ac.th/?page_id=1400" class="buttonD">รายละอียด</a>
    </div>
    <br>
    <div id=box5>
        <h2>กิจกรรมทำบุญปีใหม่ภาควิชา</h2>
    <center><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2015/03/bud_section.jpg" width="50%"></center>
    <p></br>กิจกรรมทำบุญปีใหม่ภาควิชา เป็นกิจกรรมที่ภาควิชาวิศวกรรมคอมพิวเตอร์จัดขึ้นทุกปีเป็นประจำเพื่อความเป็นสิริมงคลแก่คณาจารย์ นิสิต และเจ้าหน้าที่ในวันขึ้นปีใหม่ของทุกๆ ปี</p>
    <a href="https://www.cpe.ku.ac.th/?page_id=1434" class="buttonD">รายละอียด</a>
    </div>
</body>

app/views/static_pages/admission.html.erb
<% provide(:title, 'Admission') %>
<!--<!DOCTYPE html>-->
<!--<html>-->

<title>Admission</title>
<!--<link rel="stylesheet" href="admission.css">-->
<head>
<h1>
 Admission
</h1>
</head>
<body>
    <div>
        
    <img src="http://d251anpwg4t4cw.cloudfront.net/static/img/main/background/show_1-md.jpg" width=90%>
   
    </div>
    <br>
    <br>
    <a> โครงการรับตรง KU Admission          </a><a href="https://admission.ku.ac.th/adm/kuad/" class="button">เข้าระบบรับสมัคร</a>
     <br>
     <br>
     <a>โควตาพิเศษ (มัธยมศึกษาในท้องถิ่น)          </a><a href="https://admission.ku.ac.th/adm/provinces/" class="button">เข้าระบบรับสมัคร</a>
     <br>
     <br>
     <a>โควตานักกีฬา          </a><a  href="https://admission.ku.ac.th/adm/sport/" class ="button">เข้าระบบรับสมัคร</a>
     <br>
     <br>
     <a>โควตาสาธิตเกษตร          </a><a href="https://admission.ku.ac.th/adm/kus/" class="button">เข้าระบบรับสมัคร</a>
     <br>
     <br>
     <a>ข้อมูลการเข้าศึกษาต่อมหาวิทยาลัยเกษตรศาสตร์          </a><a href="https://admission.ku.ac.th/" class="button">คลิก</a>

</body>
<!--</html>-->

app/views/static_pages/charity.html.erb
<center><h1>กิจกรรมสาธารณะประโยชน์</h1></center>
<body>
    <div id=box1>
    <h2>Barcamp Bangkhen</h2>
    <center><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2015/03/1.jpg" width="50%"></center>
    <p><br>
        Barcamp บาร์แคมป์ คือกิจกรรมสัมมนาเปิดกว้างสำหรับทุกคน ผู้เข้าร่วมงานทุกๆ คน มาร่วมพูดคุย แลกเปลี่ยน สร้างเครือข่าย เรียนรู้และทำงานร่วมกัน แม้ว่าบาร์แคมป์ส่วนใหญ่จะเป็นการรวมกลุ่มของผู้ที่สนใจด้านเทคโนโลยี แต่หัวข้อในการพูดคุยสนทนานั้นไม่มีขอบเขตจำกัด ผู้เข้าร่วมงานสามารถร่วมพูดคุยในหัวข้อใดๆ ก็ได้ โดยผู้เข้าร่วมงานทุกคนจะร่วมกันเลือกหัวข้อที่น่าสนใจ

Barcamp Bangkhen คือ Barcamp ที่จัดขึ้นโดยกลุ่มนิสิตคณะวิศวกรรมศาสตร์ ภาควิชาวิศวกรรมคอมพิวเตอร์ มหาวิทยาลัยเกษตรศาสตร์ เพื่อเป็นศูนย์กลางให้ผู้ที่สนใจเข้ามาร่วมแลกเปลี่ยนความคิดเห็นและประสบการณ์ในงานบาร์แคมป์


    </p>
    <a href="https://www.cpe.ku.ac.th/?page_id=1415" class="buttonD">รายละอียด</a>
    </div>
</body>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact Us</h1>
    <p>
        <br>ภาควิชาวิศวกรรมคอมพิวเตอร์ คณะวิศวกรรมศาสตร์
        <br>มหาวิทยาลัยเกษตรศาสตร์ (วิทยาเขตบางเขน)
        <br>เลขที่ 50 ถนนงามวงศ์วาน แขวงลาดยาว
        <br>เขตจตุจักร กรุงเทพ ฯ 10900
        <br>โทร. 0-2797-0999 ต่อ 1403-04 1450
    </p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<style>
.mySlides {display:none;}
</style>
<body>



<div class="photo_anime_show">
  <img class="mySlides" src="https://www.cpe.ku.ac.th/wp-content/uploads/2014/08/logo_blue2-1.jpg" >
  <img class="mySlides" src="https://www.cpe.ku.ac.th/wp-content/uploads/2014/09/IMG_1242-960x350.jpg">
  <img class="mySlides" src="http://www.mp.kus.ku.ac.th/2012/images/slide/12.png">
    <img class="mySlides" src="https://www.cpe.ku.ac.th/wp-content/uploads/2014/09/IMG_3138-960x350.jpg">
    <img class="mySlides" src="https://www.cpe.ku.ac.th/wp-content/uploads/2015/03/exceed_section.jpg">
</div>

<script>
var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}    
    x[myIndex-1].style.display = "block";  
    setTimeout(carousel, 2000); // Change image every 2 seconds
}
</script>

<h1 style="text-align: center">Welcome to Department of Computer Engineering of Kasetsart University</h1>


</body>

app/views/static_pages/meeting.html.erb
<center><h1>ความร่วมมือทางวิชาการและการประชุม</h1></center>
<body>
    <div id=box1>
    <h2>Connek</h2>
    <center><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2015/03/img_preview_connek.jpg" width="50%"></center>
    <p><br>
        ConneK (Connections of CU and KU Computer Engineering Students) เป็นโครงการสานสัมพันธ์ของนิสิตวิศวกรรมคอมพิวเตอร์ จุฬาลงกรณ์มหาวิทยาลัย – มหาวิทยาลัยเกษตรศาสตร์ ที่เปิดโอกาสให้นิสิตของทั้งสองมหาวิทยาลัยได้มาทำความรู้จักกัน ผ่านการทำกิจกรรมและการแข่งขันกีฬาร่วมกัน KonneC (เมื่อมหาวิทยาลัยเกษตรศาสตร์เป็นเจ้าภาพ) หรือ ConneK (เมื่อจุฬาลงกรณ์มหาวิทยาลัยเป็นเจ้าภาพ) จัดขึ้นครั้งแรกเมื่อปี พ.ศ.2553 โดยในครั้งแรก จุฬาลงกรณ์มหาวิทยาลัย เป็นเจ้าภาพจัดโครงการ ตั้งแต่ครั้งนั้น ทั้งสอง มหาวิทยาลัยก็สลับกันเป็นเจ้าภาพมาโดยตลอด

บน้องๆ เพื่อนำไปใช้ในการทำโปรเจค
    </p>
    <a href="https://www.cpe.ku.ac.th/?page_id=1309" class="buttonD">รายละอียด</a>
    </div>
</body>

app/views/static_pages/triumph.erb
<!DOCTYPE html>
<html>
<head>
<style>

</style>
</head>
<body>

<h1>Triumph Motorcycle Scholarships</h1>
<img src="http://iup.eng.ku.ac.th/images/1797491_10201468084768148_1854041527_n.jpg">




</body>
</html>

app/views/static_pages/triumph.html.erb
<% provide(:title, 'Triumph') %>
<h1>Triumph Motorcycle Scholarships</h1>
<img src="http://iup.eng.ku.ac.th/images/1797491_10201468084768148_1854041527_n.jpg">

app/views/static_pages/tuitionscholar.erb
<!DOCTYPE html>
<html>
<head>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}
</style>
</head>
<body>
<h1>Tuition Fee and Scholarships</h1>
<h2>International Undergraduate Program (IUP) Fees</h2>
<p>Semester Fees</p>

<table>
  <tr>
    <th>Semester Fees</th>
    <th>Thai Baht/semester</th>

  </tr>
  <tr>
    <td>Tuition Fee (flat rate)</td>
    <td>56,000</td>

  </tr>
  <tr>
    <td>University Support Fee</td>
    <td>4,700</td>

  </tr>

  <tr>
    <th>Total</th>
    <th>60,700</th>

  </tr>
</table>
<p><br>Summer Fees</br></p>

<table>
  <tr>
    <th>Summer Fees</th>
    <th>Thai Baht/semester</th>

  </tr>
  <tr>
    <td>Tuition Fee (flat rate)</td>
    <td>21,000</td>

  </tr>
  <tr>
    <td>University Support Fee</td>
    <td>2,000</td>

  </tr>

  <tr>
    <th>Total</th>
    <th>23,000</th>

  </tr>
</table>

<h2><br>Scholarships</br></h2>
<p>1. Excellent Student Scholarships</p>
<p>2. Internship Abroad Scholarships</p>
<p>3. Student Exchange Scholarships
<p>4. AEC Student Exchange Scholarships</p>
<p>5. Scholarships from our partners e.g., <a href="triumph">Triumph Motorcycles, Thailand</a> (<a href="http://www.triumphmotorcycles.com/">http://www.triumphmotorcycles.com</a>)</p>
<p>More Information (iup@ku.ac.th)</p>



</body>
</html>

app/views/static_pages/tuitionscholar.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}
</style>
</head>
<body>
<h1>Tuition Fee and Scholarships</h1>
<h2 style = " text-align: left">International Undergraduate Program (IUP) Fees</h2>
<p>Semester Fees</p>

<table>
  <tr>
    <th>Semester Fees</th>
    <th>Thai Baht/semester</th>

  </tr>
  <tr>
    <td>Tuition Fee (flat rate)</td>
    <td>56,000</td>

  </tr>
  <tr>
    <td>University Support Fee</td>
    <td>4,700</td>

  </tr>

  <tr>
    <th>Total</th>
    <th>60,700</th>

  </tr>
</table>
<p><br>Summer Fees</br></p>

<table>
  <tr>
    <th>Summer Fees</th>
    <th>Thai Baht/semester</th>

  </tr>
  <tr>
    <td>Tuition Fee (flat rate)</td>
    <td>21,000</td>

  </tr>
  <tr>
    <td>University Support Fee</td>
    <td>2,000</td>

  </tr>

  <tr>
    <th>Total</th>
    <th>23,000</th>

  </tr>
</table>

<h2 style = " text-align: left"><br>Scholarships</br></h2>
<p>1. Excellent Student Scholarships</p>
<p>2. Internship Abroad Scholarships</p>
<p>3. Student Exchange Scholarships
<p>4. AEC Student Exchange Scholarships</p>
<p>5. Scholarships from our partners e.g., <a href="http://finalisp-aommoacloud9.c9users.io:8080/static_pages/triumph">Triumph Motorcycles, Thailand</a> (<a href="http://www.triumphmotorcycles.com/">http://www.triumphmotorcycles.com</a>)</p>
<p>More Information (iup@ku.ac.th)</p>



</body>
</html>